Cover/Controllers/FriendController.cs
using Cover.Domain.Models;
using Cover.Domain.Services;
using Cover.Models;
using Cover.Neo4J.Domain.Core.Repository;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cover.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class FriendController : Controller
    {
        private readonly UserService _userService;
        private readonly PostService _postService;
        private readonly UserRepository _userRepository;

        public FriendController(UserService userService, PostService postService, UserRepository userRepository)
        {
            _userService = userService;
            _postService = postService;
            _userRepository = userRepository;
        }

        [HttpGet]
        public async Task<IActionResult> Friends()
        {
            var friends = (await _userService.GetByLoginAsync(User.Identity.Name)).Friends;

            return View(friends);
        }

        [HttpGet]
        [Route("/Profile/{Login}")]
        public async Task<IActionResult> Profile(string login)
        {
            if (User.Identity.Name == login)
            {
                return RedirectToAction("MyPage", "Home");
            }

            var user = await _userService.GetByLoginAsync(login);
            var currentUser = await _userService.GetByLoginAsync(User.Identity.Name);

            var model = new UserPageViewModel
            {
                User = user,
                Posts = (await _postService.GetAsync()).Where(p => p.OwnerUserName == user.Login),
                Path = _userRepository.GetPathLength(currentUser, user)
            };

            return View(model);
        }

        [HttpGet]
        [Route("/AddFriend")]
        public async Task<EmptyResult> AddFriend(string Id)
        {
            var user = await _userService.GetByLoginAsync(User.Identity.Name);
            var friendUser = await _userService.GetAsync(Id);
            var friend = new Friend()
            {
                friendId = Id,
                FriendLogin = friendUser.Login,
                FriendName = friendUser.Name,
                FriendSurname = friendUser.Surname
            };
            if (user.Friends == null)
            {
                user.Friends = new List<Friend>();
            }

            ((List<Friend>)user.Friends).Add(friend);

            await _userService.UpdateAsync(user);

            _userRepository.CreateFriendsRelations(user, friendUser);
            return new EmptyResult();
        }
    }
}

Cover/Views/Friend/Friends.cshtml
@model IEnumerable<Friend>

@{
    ViewData["Title"] = "Friends";
}

    <div class="row p-0 m-0 d-flex flex-column bg-light">
        <div class="row m-0 p-0">
            <h2>Friends</h2>
        </div>

        @if (Model == null)
        {
            <div class="row p-0 m-0">
                <h3>No friends</h3>
            </div>
        }
        else
        {

            @foreach (var friend in Model)
            {
                <div class="row p-0 m-0 border-bottom border-dark">
                    <div class="col-1 bg-dark" style="width:50px;">

                    </div>
                    <div class="col">
                        <a class="page-link" asp-controller="Friend" asp-action="Profile" asp-route-Login="@friend.FriendLogin">
                            @friend.FriendName @friend.FriendSurname

                        </a>
                    </div>
                </div>
            }
        }
    </div>

Cover/Views/Friend/Profile.cshtml
@model UserPageViewModel
@{
    ViewData["Title"] = Model.User.Name + " " + Model.User.Surname;
}

<div class="row d-flex flex-column bg-light m-0 p-0">
    <div class="row justify-content-start m-0 p-0">
        <h2>@Model.User.Name @Model.User.Surname</h2>
    </div>
    <div class="row d-flex flex-row m-0 p-0">
        <div class="card bg-dark text-white w-100">
            <div class="card-body">
                <div class="row">
                    Mail: @Model.User.Email
                </div>
                <div class="row">
                    Age: @Model.User.Age
                </div>
                <div class="row">
                    Date of birth:  @Model.User.DateOfBirth.ToString("dd/MM")
                </div>
                <div>
                    Connetion: @Model.Path
                </div>
            </div>
        </div>
    </div>
    <div style="border-bottom:1px solid #000;" class="w-100 mb-2"></div>
    <div class="row d-flex flex-column align-content-center">
        @{await Html.RenderPartialAsync("../Home/Posts", Model.Posts);}
    </div>
</div>